### ISSUE TITLE
add license? also suggestions for Dockerfile / build

### ISSUE THREAD

**Issue by ldemailly** [tonymet/gcloud-go#1]
Thanks for doing this

Can you add a license (MIT/bsd/Apache...) ?

For your Dockerfile, have a look at https://laurentsv.com/blog/2024/06/25/stop-the-go-and-docker-madness.html

in particular you don't need to copy certs anymore if you use 
```
import _ "golang.org/x/crypto/x509roots/fallback" // CA bundle for FROM Scratch
```

And for /tmp you can/should just 
VOLUME /tmp

cheers

**Comment by tonymet** [comment]
Great tip on both fronts. I think I clobbered the license from earlier. I’ll keep GPL3.  I appreciate the support and let me know how you’re using the project.

**Comment by tonymet** [comment]
Excellent guidance and thanks @ldemailly

**Comment by ldemailly** [comment]
most welcome, thanks for the quick updates, a little follow up https://github.com/tonymet/gcloud-go/commit/24a5bbb204da6cd93c2d0bb3202007df426adfd7#commitcomment-148491149

**Comment by ldemailly** [comment]
Also ... you picked GPL... that means it can't be adopted by many companies and also lessen the chance of contributions (or fall back into gcloud offering) - is it a deliberate choice?

**Comment by tonymet** [comment]
Thanks I gave it a thought as I also had those considerations. I prefer encouraging the contributions to stay open. If I see a lot of commercial use cases I’ll think about another licensing approach.

**Comment by ldemailly** [comment]
well the thing is employees approved to work on opensource (already a smaller set) are typically not allowed to touch any gpl code so I don’t think you’ll see much adoption/use case. this being said maybe it can be just maintained by you and used without contributions from others

**Comment by tonymet** [comment]
That’s good guidance. Let’s see how it plays out and I’ll have some good contingencies in place.
